---
Name: event-tickets
---
#XD\Events\Model\EventPage:
#  extensions:
#    - 'Broarm\EventTickets\TicketExtension'
#XD\Events\Model\EventPageController:
#  extensions:
#    - 'Broarm\EventTickets\TicketControllerExtension'
#    - 'Broarm\EventTickets\RegisterStep'
#    - 'Broarm\EventTickets\SummaryStep'
#    - 'Broarm\EventTickets\SuccessStep'
Broarm\EventTickets\Checkout\Steps\CheckoutSteps:
  checkout_steps:
    - register
    - summary
    - success
SilverStripe\SiteConfig\SiteConfig:
  extensions:
    - Broarm\EventTickets\Extensions\SiteConfigExtension
SilverStripe\Omnipay\Model\Payment:
  extensions:
    - Broarm\EventTickets\Extensions\TicketPayment
SilverStripe\Forms\GridField\GridFieldDetailForm_ItemRequest:
  extensions:
    - Broarm\EventTickets\Extensions\GridFieldDetailFormItemRequestExtension